#!/bin/bash

DIR_HOME=/home/openwrt
DIR_ROOT=$DIR_HOME/trunk

# getting source
git clone git://git.openwrt.org/openwrt.git $DIR_ROOT
git clone https://github.com/aa65535/openwrt-chinadns.git $DIR_ROOT/package/chinadns-c
git clone https://github.com/aa65535/openwrt-shadowsocks.git $DIR_ROOT/package/shadowsocks-libev
git clone https://github.com/aa65535/openwrt-shadowvpn.git $DIR_ROOT/package/shadowvpn

ln -s $DIR_HOME/dl $DIR_ROOT/dl

# scripts - mn
touch $DIR_ROOT/mn && chmod +x $DIR_ROOT/mn
echo "#!/bin/bash" >> $DIR_ROOT/mn
echo "" >> $DIR_ROOT/mn
