#!/bin/bash

GIT_ROOT=/home/bkup

cd /var/www/fonts/font-awesome && git pull

rsync /etc/crontab $GIT_ROOT/xvm/etc/
rsync -a --delete /var/www/ $GIT_ROOT/xvm/var/www/

cd $GIT_ROOT && git pull && git add * && git commit -m "xvm daily bkup" && git push
