#!/bin/bash

DIR_ROOT=/home/openwrt/14.07
DIR_PKG=$DIR_ROOT/package
DIR_BIN=$DIR_ROOT/bin/ar71xx
DIR_GIT=/home/bkup
CONFIG=$DIR_ROOT/n750-ss.config

cd $DIR_PKG/chinadns-c && git pull
cd $DIR_PKG/openwrt-dist-luci && git pull
cd $DIR_PKG/shadowsocks-libev && git pull
cd $DIR_PKG/shadowvpn && git pull
cd $DIR_ROOT && git pull

cp -f $CONFIG $DIR_ROOT/.config
$DIR_ROOT/scripts/feeds update -a
$DIR_ROOT/scripts/feeds install -a
make defconfig
make prereq
cp -f $DIR_ROOT/.config $CONFIG
make

mv -f $DIR_BIN/openwrt-ar71xx-generic-mynet-n750-squashfs-sysupgrade.bin $DIR_BIN/openwrt-ar71xx-generic-mynet-n750-squashfs-sysupgrade-shadowsocks.bin
scp $DIR_BIN/openwrt-ar71xx-generic-mynet-n750-squashfs-sysupgrade-shadowsocks.bin xvm:/var/www/router/firmware/14.07/

touch $DIR_ROOT/timetag && echo `date` > $DIR_ROOT/timetag
scp $DIR_ROOT/timetag xvm:/var/www/router/firmware/
rm $DIR_ROOT/timetag
