#!/bin/bash

DIR_HOME=/home/openwrt
DIR_ROOT=$DIR_HOME/trunk

cd $DIR_ROOT/package/chinadns-c && git pull
cd $DIR_ROOT/package/shadowsocks-libev && git pull
cd $DIR_ROOT/package/shadowvpn && git pull

cd $DIR_ROOT && git pull
./scripts/feeds update -a
./scripts/feeds install -a
make defconfig
make prereq
make menuconfig
