#!/bin/bash

PATH="/var/www/router/shadowsocks";

if [ -e $PATH/ignore.list ]; then
	/bin/mv -f $PATH/ignore.list $PATH/ignore.list.old

fi

while [ ! -s "$PATH/ignore.list" ]; do
	/usr/bin/curl 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | /usr/bin/awk -F\| '/CN\|ipv4/ { printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > $PATH/ignore.list;
done

/bin/echo "100.100.100.100/32" >> $PATH/ignore.list;
/usr/bin/python $PATH/scripts/ip.py >> $PATH/ignore.list;
/bin/cat  $PATH/ip-cn >> $PATH/ignore.list;
/bin/cat  $PATH/ip-ptc >> $PATH/ignore.list;
