#!/bin/bash

PATH="/var/www/router/shadowsocks";

if [ -e $PATH/ignore.list ]; then
	/bin/mv -f $PATH/ignore.list $PATH/ignore.list.old

fi

/usr/bin/curl 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | /usr/bin/awk -F\| '/CN\|ipv4/ { printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > $PATH/ignore.list;


if [ -s "$PATH/ignore.list" ]; then
	/bin/cat $PATH/ip-vps >> $PATH/ignore.list;
	
else
	/bin/rm $PATH/ignore.list;
	/usr/bin/wget -O- 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | /usr/bin/awk -F\| '/CN\|ipv4/ { printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > $PATH/ignore.list;

	if [ -s "$PATH/ignore.list" ]; then
		/bin/cat $PATH/ip-vps >> $PATH/ignore.list;

	else
		/bin/rm $PATH/ignore.list;
		sleep 30;
		/bin/sh $PATH//scripts/fetch_shadowsocks_ignore_list;

	fi
	
fi
